In [1]:
!pip install toqito

You should consider upgrading via the '/Users/Shared/Drive/Qiskit/qiskitenv/bin/python3 -m pip install --upgrade pip' command.


In [2]:
# Calculate the classical and quantum value of the CHSH game.
import numpy as np
from toqito.nonlocal_games.xor_game import XORGame

# The probability matrix.
prob_mat = np.array([[1/4, 1/4], [1/4, 1/4]])

# The predicate matrix.
pred_mat = np.array([[0, 0], [0, 1]])

# Define CHSH game from matrices.
chsh = XORGame(prob_mat, pred_mat)

chsh.classical_value()
# 0.75
chsh.quantum_value()
# 0.8535533


0.8535533908447773

In [3]:
from toqito.states import basis
# |0>
basis(3, 2)

array([[0],
       [0],
       [1]])

In [4]:
e_0, e_1 = basis(2, 0), basis(2, 1)
u_0 = 1/np.sqrt(2) * (np.kron(e_0, e_0) + np.kron(e_1, e_1))
u_0

array([[0.70710678],
       [0.        ],
       [0.        ],
       [0.70710678]])

In [5]:
rho_0 = u_0 @ u_0.conj().T
rho_0

array([[0.5, 0. , 0. , 0.5],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0.5, 0. , 0. , 0.5]])

In [6]:
from toqito.states import bell
import numpy as np
bell(0)

array([[0.70710678],
       [0.        ],
       [0.        ],
       [0.70710678]])

In [7]:
from toqito.states import ghz
ghz(2, 3)

<8x1 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in List of Lists format>

In [8]:
from toqito.states import ghz
ghz(4, 7, np.array([1, 2, 3, 4]) / np.sqrt(30))

<16384x1 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in List of Lists format>

In [9]:
from toqito.states import bell
from toqito.state_props import is_pure
rho = bell(0) @ bell(0).conj().T
is_pure(rho)

True

In [10]:
from toqito.states import bell
from toqito.state_props import is_ppt
rho = bell(2) @ bell(2).conj().T
is_ppt(rho)

False

In [11]:
import numpy as np
from toqito.state_props import is_separable
from toqito.states import tile
rho = np.identity(9)
for i in range(5):
   rho = rho - tile(i) @ tile(i).conj().T
rho = rho / 4
is_separable(rho)

False

In [12]:
is_ppt(rho)

True

In [13]:
from toqito.states import bell
from toqito.state_metrics import fidelity
import numpy as np
# Define two identical density operators.
rho = bell(0)*bell(0).conj().T
sigma = bell(0)*bell(0).conj().T
# Calculate the fidelity between `rho` and `sigma`
np.around(fidelity(rho, sigma), decimals=2)

1.0

In [14]:
from toqito.channels import partial_trace
import numpy as np
test_input_mat = np.array(
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
)
partial_trace(test_input_mat)

array([[ 7, 11],
       [23, 27]])

In [15]:
partial_trace(test_input_mat, sys=[0])

array([[12, 14],
       [20, 22]])

In [16]:
from toqito.channels import partial_transpose
import numpy as np
test_input_mat = np.arange(1, 17).reshape(4, 4)
partial_transpose(test_input_mat)

array([[ 1,  5,  3,  7],
       [ 2,  6,  4,  8],
       [ 9, 13, 11, 15],
       [10, 14, 12, 16]])

In [17]:
partial_transpose(test_input_mat, sys=[0])

array([[ 1,  2,  9, 10],
       [ 5,  6, 13, 14],
       [ 3,  4, 11, 12],
       [ 7,  8, 15, 16]])

In [18]:
import numpy as np
prob_mat = np.array([[1 / 4, 1 / 4], [1 / 4, 1 / 4]])

In [19]:
import numpy as np
num_alice_inputs, num_alice_outputs = 2, 2
num_bob_inputs, num_bob_outputs = 2, 2
pred_mat = np.zeros(
    (num_alice_outputs, num_bob_outputs, num_alice_inputs, num_bob_inputs)
)
for a_alice in range(num_alice_outputs):
    for b_bob in range(num_bob_outputs):
        for x_alice in range(num_alice_inputs):
            for y_bob in range(num_bob_inputs):
                if a_alice ^ b_bob == x_alice * y_bob:
                    pred_mat[a_alice, b_bob, x_alice, y_bob] = 1

In [39]:
import numpy as np
from toqito.nonlocal_games.nonlocal_game import NonlocalGame
chsh = NonlocalGame(prob_mat, pred_mat)
np.around(chsh.quantum_value_lower_bound(), decimals=2)

0.85