In [1]:
import numpy as np
from toqito.matrix_ops import tensor
def kraus_to_channel(
    kraus_list: list[tuple[np.ndarray, np.ndarray]]
) -> np.ndarray:
    """
    Converts a collection of Kraus operators into the corresponding quantum channel (superoperator).
    :param kraus_list: List of tuples (A, B) where A and B are Kraus operators as numpy arrays
    :return: The superoperator as a numpy array
    """
    super_op = sum(tensor(B, A.conj()) for A, B in kraus_list)
    return super_op

In [2]:
dim = 2**2
kraus_list = [np.random.randint(-1, 4, (2, dim, dim)) for _ in range(12)]

In [3]:
import toqito.state_ops
vector = np.random.randint(-3, 3, (dim, 1))
dm = toqito.matrix_ops.to_density_matrix(vector)
vec_dm = toqito.matrix_ops.vec(dm)


In [4]:
superop = kraus_to_channel(kraus_list)
toqito.matrix_ops.unvec(superop @ vec_dm)

array([[565, 436, 498, 665],
       [771, 942, 734, 906],
       [452, 575, 628, 760],
       [498, 740, 709, 613]])

In [5]:
sum(A @ dm @ B.conj().T for A, B in kraus_list)

array([[565, 436, 498, 665],
       [771, 942, 734, 906],
       [452, 575, 628, 760],
       [498, 740, 709, 613]])

In [6]:
sum(B @ dm @ A.T for A, B in kraus_list)

array([[565, 771, 452, 498],
       [436, 942, 575, 740],
       [498, 734, 628, 709],
       [665, 906, 760, 613]])